#!/bin/bash
set -e

## Operational variables
COMMAND=$0
RECURSIVE="false"
ANALYZE="false"
DEPENDENCIES=("jq")

SUPPORTED_FILES="mkv mp4"

## Prints help text.
help() {
	echo "fencoder - FFmpeg wrapper for automatically encoding video files"
	echo
	echo "Usage: $FENCODER_COMMAND [FILES] [OPTIONS]"
	echo
	echo "Options:"
	echo "   -a --analyze    Only analyze the video files, don't encode"
	echo "   -r --recursive  Look in subdirectories for video files"
}

# Checks that we have access to all required tools.
check_dependencies() {
	set +e
	for dep in "${DEPENDENCIES[@]}"; do
		which $dep
		if [ $? -ne 0 ]; then
			echo "ERROR: dependency not installed: $dep"
			exit 1
		fi
	done
	set -e
}

## Checks the initial provided file list to make sure we can find all the files,
## and make sure all given files are supported.
check_input_files() {
	for file in "${input_files[@]}"; do
		if [ -f $file ]; then
			ext="${file##*.}"
			if [[ $SUPPORTED_FILES != *"$ext"* ]]; then
				echo "ERROR: unsupported video file: $file"
				exit 1
			fi
		elif [ -d $file ]; then
			if [ "$RECURSIVE" == "false" ]; then
				echo "ERROR: input is a directory: $file"
				echo "Use -r to scan recursively"
				exit 1
			fi
		else
			echo "ERROR: file not found: $file"
			exit 1
		fi
	done
}

## Recursively expands out any directories we were given.
expand_dirs() {
	for file in $@; do
		ext="${file##*.}"
		if [ -f $file ]; then
			if [[ $SUPPORTED_FILES == *"$ext"* ]]; then
				files+=($file)
			fi
		elif [ -d $file ]; then
			expand_dirs $file/*
		else
			echo "ERROR: file not found: $file"
			exit 1
		fi
	done
}

analyze() {
	echo "Analyzing $1..."
}

encode() {
	echo "Encoding $1..."
}

main() {
	declare -a input_files

	check_dependencies

	# Parse CLI options
	for opt in $@ ; do
		if [[ $opt =~ ^-.* ]]; then
			case $opt in
				"-a" | "--analyze")
					ANALYZE="true"
					;;
				"-r" | "--recursive")
					RECURSIVE="true"
					;;
				"-h" | "--help")
					help
					exit
					;;
				*)
					echo "ERROR: unknown option: $opt"
					exit 1
					;;
			esac
		else
			input_files+=($opt)
		fi
	done

	if [ ${#input_files[@]} -eq 0 ]; then
		echo "ERROR: no input files given"
		exit 1
	fi

	# Initial check of provided files
	check_input_files

	# Expand out directories
	declare -a files
	expand_dirs "${input_files[@]}"

	# Analyze each file
	for file in "${files[@]}"; do
		analyze $file
	done
	if [ "$ANALYZE" == "true" ]; then
		exit
	fi

	# Encode each file
	for file in "${files[@]}"; do
		encode $file
	done

}

main "$@"
